
-- 사용자 함수 FUNC1 정의
CREATE OR REPLACE FUNCTION FUNC1
RETURN VARCHAR2  -- 반환타입에서는 크기를 명시하지 않는다.
IS
BEGIN
    RETURN 'Hello World';
END;

-- 사용자 함수 FUNC1 호출
SELECT FUNC1() FROM DUAL;



-- 사용자 함수 FUNC2 정의
-- 사원번호를 전달하면 해당 사원의 FULL_NAME(Steven King)을 반환하는 함수

-- 사용자 함수의 파라미터는 IN/OUT 표기가 없다.
-- 입력 파라미터 형식으로 사용된다.

CREATE OR REPLACE FUNCTION FUNC2(EMP_ID EMPLOYEES.EMPLOYEE_ID%TYPE)
RETURN VARCHAR2
IS
    FNAME EMPLOYEES.FIRST_NAME%TYPE;
    LNAME EMPLOYEES.LAST_NAME%TYPE;
BEGIN

    SELECT FIRST_NAME, LAST_NAME
      INTO FNAME, LNAME
      FROM EMPLOYEES
     WHERE EMPLOYEE_ID = EMP_ID;

    RETURN FNAME || ' ' || LNAME;

END;

-- 사용자 함수 FUNC2 호출
SELECT FUNC2(100)
  FROM EMPLOYEES
 WHERE EMPLOYEE_ID = 100;



-- 사용자 함수 FUNC3 정의
-- 사원번호를 전달하면 해당 사원의 연봉이 15000 이상이면 '고액연봉', 아니면 '보통연봉'을 반환하는 함수
CREATE OR REPLACE FUNCTION FUNC3(EMP_ID EMPLOYEES.EMPLOYEE_ID%TYPE)
RETURN VARCHAR2
IS
    MESSAGE VARCHAR2(12 BYTE);
    SAL EMPLOYEES.SALARY%TYPE;
BEGIN
    SELECT SALARY
      INTO SAL
      FROM EMPLOYEES
     WHERE EMPLOYEE_ID = EMP_ID;
     
    IF SAL >= 15000 THEN
        MESSAGE := '고액연봉';
    ELSE
        MESSAGE := '보통연봉';
    END IF;
    RETURN MESSAGE;
END;
        
-- 사용자 함수 FUNC3 호출
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, FUNC3(EMPLOYEE_ID)
  FROM EMPLOYEES;


-- 올림처리하는 함수 만들기
CREATE OR REPLACE FUNCTION MY_CEIL(NUM1 NUMBER, DIGIT NUMBER)
RETURN NUMBER
IS
BEGIN
    RETURN CEIL(NUM1 * POWER(10, DIGIT)) / POWER(10, DIGIT);
END;

SELECT MY_CEIL(1.111, 2),
       MY_CEIL(111.111, 1),
       MY_CEIL(111.111, -2),
       MY_CEIL(111.111, -1)
       FROM DUAL;
       
CREATE OR REPLACE FUNCTION MY_FLOOR(NUM1 NUMBER, NUM2 NUMBER)
RETURN NUMBER
IS
BEGIN
    RETURN FLOOR(NUM1 * POWER(10, NUM2)) / POWER(10, NUM2);
END;

SELECT MY_FLOOR(1.111, 2)
FROM DUAL;