DROP TABLE PROCEEDING_TBL;
DROP TABLE PROJECT_TBL;
DROP TABLE EMPLOYEE_TBL;
DROP TABLE DEPARTMENT_TBL;

CREATE TABLE DEPARTMENT_TBL(
    DEPT_NO VARCHAR2(15 BYTE),
    DEPT_NAME VARCHAR2(30 BYTE),
    DEPT_LOCATION VARCHAR2(50 BYTE),
    CONSTRAINT PK_DEPT PRIMARY KEY(DEPT_NO)
);

CREATE TABLE EMPLOYEE_TBL(
    EMP_NO NUMBER,
    DEPT_NO VARCHAR2(15 BYTE),
    POSITION CHAR(10 BYTE),
    NAME VARCHAR2(15 BYTE),
    HIRE_DATE DATE,
    SALARY NUMBER,
    CONSTRAINT PK_EMP PRIMARY KEY(EMP_NO),
    CONSTRAINT FK_EMP_DEPT FOREIGN KEY(DEPT_NO) REFERENCES DEPARTMENT_TBL(DEPT_NO) ON DELETE SET NULL
    -- 부서가 없어지면 사원의 부서정보만 NULL 처리 됨
);

CREATE TABLE PROJECT_TBL(
    PJT_NO NUMBER,
    PJT_NAME VARCHAR2(30 BYTE),
    BEGIN_DATE DATE,
    END_DATE DATE,
    CONSTRAINT PK_PJT PRIMARY KEY(PJT_NO)
);

CREATE TABLE PROCEEDING_TBL(
    PCD_NO NUMBER,
    EMP_NO NUMBER,
    PJT_NO NUMBER,
    PJT_STATE NUMBER NOT NULL,
    CONSTRAINT PK_PCD PRIMARY KEY(PCD_NO),
    CONSTRAINT FK_PCD_EMP FOREIGN KEY(EMP_NO) REFERENCES EMPLOYEE_TBL(EMP_NO) ON DELETE SET NULL,
    CONSTRAINT FK_PCD_PJT FOREIGN KEY(PJT_NO) REFERENCES PROJECT_TBL(PJT_NO) ON DELETE SET NULL
);