
DROP TABLE SUBJECT;
DROP TABLE PROF_INFO;
DROP TABLE STUDENT_INFO;

CREATE TABLE STUDENT_INFO(
    STU_NUM VARCHAR2(5 BYTE),
    STU_NAME VARCHAR2(6 BYTE),
    STU_AGE NUMBER,
    CONSTRAINT PK_INFO PRIMARY KEY(STU_NUM)
);

CREATE TABLE PROF_INFO(
    SUB_CODE VARCHAR2(1 BYTE),
    PROF_SUBNAME VARCHAR2(4 BYTE),
    PROF_NAME VARCHAR2(6 BYTE),
    CONSTRAINT PK_PROF PRIMARY KEY(SUB_CODE)
);

CREATE TABLE SUBJECT(
    SUB_NUM NUMBER NOT NULL,
    STU_NUM VARCHAR2(5 BYTE) NOT NULL,
    SUB_CODE VARCHAR2(1 BYTE) NOT NULL,
    CONSTRAINT PK_SUB_INFO PRIMARY KEY(SUB_NUM),
    CONSTRAINT FK_SUB_INFO FOREIGN KEY(STU_NUM) REFERENCES STUDENT_INFO(STU_NUM) ON DELETE CASCADE,
    CONSTRAINT FK_SUB_PROF FOREIGN KEY(SUB_CODE) REFERENCES PROF_INFO(SUB_CODE) ON DELETE CASCADE
);