-- 이너 조인
-- 표준 문법
SELECT D.DEPT_NO, D.DEPT_NAME, E.NAME, E.EMP_NO
  FROM DEPARTMENT_TBL D INNER JOIN EMPLOYEE_TBL E
    ON D.DEPT_NO = E.DEPART;
-- 오라클 문법
SELECT D.DEPT_NO, D.DEPT_NAME, E.NAME, E.EMP_NO
  FROM DEPARTMENT_TBL D, EMPLOYEE_TBL E
 WHERE D.DEPT_NO = E.DEPART;
 
-- 왼쪽 외부 조인
-- 표준 문법
SELECT D.DEPT_NO, D.DEPT_NAME, E.EMP_NO, E.NAME
  FROM DEPARTMENT_TBL D LEFT OUTER JOIN EMPLOYEE_TBL E
    ON D.DEPT_NO = E.DEPART;

-- 오라클 문법
SELECT D.DEPT_NO, D.DEPT_NAME, E.EMP_NO, E.NAME
  FROM DEPARTMENT_TBL D, EMPLOYEE_TBL E
 WHERE D.DEPT_NO = E.DEPART(+);
 
 
-- 오른쪽 외부조인
-- 표준문법
SELECT D.DEPT_NO, D.DEPT_NAME, E.EMP_NO, E.NAME
FROM DEPARTMENT_TBL D RIGHT OUTER JOIN EMPLOYEE_TBL E
ON D.DEPT_NO = E.DEPART;

-- 오라클로
SELECT D.DEPT_NO, D.DEPT_NAME, E.EMP_NO, E.NAME
FROM DEPARTMENT_TBL D, EMPLOYEE_TBL E
WHERE D.DEPT_NO(+) = E.DEPART;

-- 외래키 제약조건을 위반하는 데이터 삭제하기
DELETE FROM EMPLOYEE_TBL
WHERE EMP_NO = 1005; -- PK를 조건으로 사용하면 인덱스를 타기에 빠르다
DELETE FROM EMPLOYEE_TBL WHERE NAME = '김성실'; -- 인덱스를 타지 않는 일반 칼럼은 느리게 작용한다
COMMIT;

-- 외래키 제약조건의 비활성화(일시 중지)
-- 제약조건이름 : FK_EMP_DEPT
ALTER TABLE EMPLOYEE_TBL
    DISABLE CONSTRAINT FK_EMP_DEPT;

-- 외래키 제약조건이 없는 상태이므로, 제약조건을 위배하는 데이터를 입력할 수 있다.
INSERT INTO EMPLOYEE_TBL(EMP_NO, NAME, DEPART, POSITION, GENDER, HIRE_DATE, SALARY)
VALUES(EMPLOYEE_SEQ.NEXTVAL, '김성실', 5, '대리', 'F', '98/12/01', 3500000);
COMMIT;

-- 외래키 제약조건의 활성화(다시 시작)
-- 제약조건이름 : FK_EMP_DEPT
ALTER TABLE EMPLOYEE_TBL
    ENABLE CONSTRAINT FK_EMP_DEPT;
    