DROP TABLE SCHEDULE_TBL;
DROP TABLE PLAYER_TBL;
DROP TABLE EVENT_TBL;
DROP TABLE NATION_TBL;

CREATE TABLE NATION_TBL(
    N_CODE          NUMBER(3) NOT NULL,
    N_NAME          VARCHAR2(30 BYTE) NOT NULL,
    N_PARTI_PERSON  NUMBER,
    N_PARTI_EVENT   NUMBER,
    N_PREV_RANK     NUMBER,
    N_CURR_RANK     NUMBER
);

CREATE TABLE EVENT_TBL (
    E_CODE        NUMBER             NOT NULL,
    E_NAME        VARCHAR2(30 BYTE)  NOT NULL,
    E_FIRST_YEAR  NUMBER(4)          NULL,
    E_INFO        VARCHAR2(100 BYTE) NULL
);

CREATE TABLE PLAYER_TBL(
    P_CODE NUMBER(3) NOT NULL,
    P_NAME VARCHAR2(30 BYTE) NOT NULL,
    N_CODE NUMBER(3) NOT NULL,
    E_CODE NUMBER NOT NULL,
    P_RANK NUMBER,
    P_AGE  NUMBER(3)
);

CREATE TABLE SCHEDULE_TBL(
    S_NO         NUMBER(3)      NOT NULL,
    N_CODE       NUMBER(3),
    E_CODE       NUMBER,
    S_START_DATE DATE,
    S_END_DATE   DATE,
    S_INFO       VARCHAR2(100 BYTE)
);

--기본키 제거하기
ALTER TABLE NATION_TBL
    DROP PRIMARY KEY; -- 테이블의 기본키는 오직 하나기에 이름을 몰라도 가능

ALTER TABLE EVENT_TBL
    DROP PRIMARY KEY;
    
ALTER TABLE PLAYER_TBL
    DROP PRIMARY KEY;
    
ALTER TABLE SCHEDULE_TBL
    DROP PRIMARY KEY;

--기본키 추가하기
ALTER TABLE NATION_TBL
    ADD CONSTRAINT PK_NATION
        PRIMARY KEY(N_CODE);
        
ALTER TABLE EVENT_TBL
    ADD CONSTRAINT PK_EVENT
        PRIMARY KEY(E_CODE);
        
ALTER TABLE PLAYER_TBL
    ADD CONSTRAINT PK_PLAYER
        PRIMARY KEY(P_CODE);
        
ALTER TABLE SCHEDULE_TBL
    ADD CONSTRAINT PK_SCHEDULE
        PRIMARY KEY(S_NO);
        

--외래키 제거하기
ALTER TABLE PLAYER_TBL
    DROP CONSTRAINT FK_PLAYER_NATION;
ALTER TABLE PLAYER_TBL
    DROP CONSTRAINT FK_PLAYER_EVENT;
ALTER TABLE SCHEDULE_TBL
    DROP CONSTRAINT KF_SCHEDULE_NATION;
ALTER TABLE SCHEDULE_TBL
    DROP CONSTRAINT FK_SCHEUDLE_EVENT;
--외래키 생성하기
ALTER TABLE PLAYER_TBL
    ADD CONSTRAINT FK_PLAYER_NATION FOREIGN KEY(N_CODE)
        REFERENCES NATION_TBL(N_CODE)
            ON DELETE CASCADE;
            
ALTER TABLE PLAYER_TBL
    ADD CONSTRAINT FK_PLAYER_EVENT FOREIGN KEY(E_CODE)
        REFERENCES EVENT_TBL(E_CODE)
            ON DELETE CASCADE;
ALTER TABLE SCHEDULE_TBL
    ADD CONSTRAINT KF_SCHEDULE_NATION FOREIGN KEY(N_CODE)
        REFERENCES NATION_TBL(N_CODE)
            ON DELETE SET NULL; -- ON DELETE CASCADE도 가능
            
ALTER TABLE SCHEDULE_TBL
    ADD CONSTRAINT FK_SCHEDULE_EVENT FOREIGN KEY(E_CODE)
        REFERENCES EVENT_TBL(E_CODE)
            ON DELETE SET NULL; -- ON DELETE CASCADE도 가능

-- 연습 NATION_TBL의 기본키 제거
-- 외래키에 의해서 참조중인 기본키PK는 반드시 외래키를 제거한 후에 삭제할 수 있다


ALTER TABLE PLAYER_TBL
    DROP CONSTRAINT FK_PLAYER_NATION;

ALTER TABLE SCHEDULE_TBL
    DROP CONSTRAINT KF_SCHEDULE_NATION;
    
ALTER TABLE NATION_TBL
    DROP PRIMARY KEY;
    
-- 외래키 제약조건 일시중지
ALTER TABLE PLAYER_TBL
    DISABLE CONSTRAINT FK_PLAYER_EVENT;

-- 외래키 제약조건 다시 시작(활성화)
ALTER TABLE PLAYER_TBL
    ENABLE CONSTRAINT FK_PLAYER_EVENT;