--1. EMPLOYEES 테이블에서 FIRST_NAME LAST_NAME 조회하기

SELECT E.FIRST_NAME AS FNAME, E.LAST_NAME AS LNAME
  FROM HR.EMPLOYEES E;
  
-- 2. EMPLOYEES 테이블에서 DEPARTMENT_ID 중복 제거하고 조회하기

SELECT DISTINCT DEPARTMENT_ID
  FROM HR.EMPLOYEES;
  
-- 3. EMPLOYEES 테이블에서 EMPLOYEE_ID가 150인 사원 조회하기
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME
  FROM EMPLOYEES
 WHERE EMPLOYEE_ID = 150; 
 -- EMPLOYEE_ID가 숫자인지, 문자인지 미리 구분이 필요하다
  DESC EMPLOYEES; -- 구조 파악 가능
  
-- 4. EMPLOYEES 테이블에서 SALARY가 10000~20000 사이 사원 조회하기
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY BETWEEN 10000 AND 20000;

-- 5. EMPLOYEES 테이블에서 DEPARTMENT_ID가 30, 40, 50인 사원 조회하기
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, DEPARTMENT_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN(30, 40, 50);

-- 6. EMPLOYEES 테이블에서 DEPARTMENT_ID가 NULL인 사원 조회하기
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, DEPARTMENT_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NULL;

-- 7. EMPLOYEES 테이블에서 PHONE_NUMBER가 515로 시작하는 사원조회하기
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, PHONE_NUMBER
FROM EMPLOYEES
WHERE PHONE_NUMBER NOT LIKE '515%';

-- 8. EMPLOYEES 테이블을 FIRST_NAME의 가나다 순으로 정렬하여 조회하기 (오름차순)
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME
  FROM EMPLOYEES
 ORDER BY FIRST_NAME ASC; -- ASC 생략가능
 
-- 9. EMPLOYEES 테이블을 높은 SALARY 받는 사원 순으로 정렬하여 조회하기 (내림차수)
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES
ORDER BY SALARY DESC;

-- 10. (정렬기준이 2개이상) EMPLOYEES 테이블의 DEPARTMENT_ID 순으로 조회하고,
-- 동일한 DEPARTMENT_ID를 가진 사원들은 높은 SALARY 순으로 조회하기
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, DEPARTMENT_ID, SALARY
FROM EMPLOYEES
ORDER BY DEPARTMENT_ID ASC, SALARY DESC;

