DROP TABLE PRODUCT;
CREATE TABLE PRODUCT(
    CODE        VARCHAR2(2 BYTE)    NOT NULL UNIQUE,
    MODEL       VARCHAR2(10 BYTE)   NULL,
    CATEGORY    VARCHAR2(5 BYTE)    CHECK(CATEGORY = 'MAIN' OR CATEGORY = 'SUB'), -- CHECK(CATEGORY IN('MAIN', 'SUB'))
    PRICE       NUMBER              CHECK(PRICE>=0),
    AMOUNT      NUMBER(2)           CHECK(AMOUNT >=0 AND AMOUNT <=100), -- CHECK(AMOUNT BETWEEN(0 AND 100))              
    MANUFACTURED DATE
);
    
    