DROP TABLE CUSTOMER_TBL;
DROP TABLE BANK_TBL;

CREATE TABLE BANK_TBL(
     BANK_CODE VARCHAR2(20 BYTE),
     BANK_NAME VARCHAR2(30 BYTE),
    CONSTRAINT PK_BANK PRIMARY KEY(BANK_CODE)
);

CREATE TABLE CUSTOMER_TBL(
    NO           NUMBER,
    NAME         VARCHAR2(30 BYTE)      NOT NULL,
    PHONE        VARCHAR2(30 BYTE)      UNIQUE,
    AGE          NUMBER                 CHECK(AGE BETWEEN 0 AND 100),
    BANK_CODE    VARCHAR2(20 BYTE),
    CONSTRAINT PK_CUST PRIMARY KEY(NO),
    CONSTRAINT FK_CUST_BANK FOREIGN KEY(BANK_CODE) REFERENCES BANK_TBL (BANK_CODE)
);

ALTER TABLE BANK_TBL   
    ADD BANK_TEL VARCHAR2(20 BYTE) NOT NULL;
    
ALTER TABLE CUSTOMER_TBL
    DROP COLUMN AGE;

ALTER TABLE BANK_TBL
    MODIFY BANK_NAME VARCHAR2(15 BYTE);
    
-- CUSTOMER_TBL 테이블에서 고객명NAME 칼럼의 이름을 CUST_NAME 으로 변경
ALTER TABLE CUSTOMER_TBL
    RENAME COLUMN NAME TO CUST_NAME;
    
    
-- CUSTOMER_TBL 테이블에 GRADE 칼럼을 추가하기
-- GRADE 칼럼은 ("VIP', 'GOLD', 'SILVER', 'BRONZE' 중 하나의 값만 가질 수 있도록 CHECK 제약 조건을 지정
ALTER TABLE CUSTOMER_TBL
    ADD GRADE VARCHAR2(6 BYTE) CHECK(GRADE IN ('VIP', 'GOLD', 'SILVER', 'BRONZE'));
    
-- BANK_TBL 테이블의 BANK_NAME 칼럼에 NOT NULL 제약조건 추가
ALTER TABLE BANK_TBL
    MODIFY BANK_NAME VARCHAR2(15 BYTE) NOT NULL;
    
-- CUSTOMER_TBL 테이블의 NO 칼럼의 이름을 CUST_NO 로 변경
ALTER TABLE CUSTOMER_TBL
    RENAME COLUMN NO TO CUST_NO;
    
-- CUSTOMER_TBL 테이블의 PHONE 칼럼을 삭제하시오
ALTER TABLE CUSTOMER_TBL
    DROP COLUMN PHONE;

-- CUSTOMER TBL 테이블의 CUST_NAME 칼럼의 NOT NULL 제약조건을 NULL로 변경
ALTER TABLE CUSTMER_TBL
    MODIFY CUST_NAME VARCHAR2(30 BYTE) NULL;